### 注册
POST http://127.0.0.1:8888/register
Content-Type: application/json

{
  "username": "huangjg",
  "password": "123456",
  "nickname": "张三",
  "wallet_addr": "0xabcdefggggjsda2lfidsfe3vh5aisdh6fjkashf",
  "referral_code": "CJY3-UYDX"
}

### 登录
POST http://localhost:8888/login
Content-Type: application/json

{
  "username": "huangjg",
  "password": "123456",
  "captcha_id": "mzG7D9F3GzBSnrNTdo4k",
  "captcha_code": "7"
}

### 获取用户信息
GET http://127.0.0.1:8888/v1/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Imh1YW5namciLCJ0b2tlbl92ZXJzaW9uIjoyLCJpc3MiOiJnby1hZG1pbi1taWNyby91c2VyIiwiZXhwIjoxNzY4ODAyODIzLCJpYXQiOjE3Njg3MTY0MjN9.kcjOWuaK6TJ4FdnZJcc_OiSY3HzKGq0kqAOAvuQa4NU


### 更改用户信息
POST http://127.0.0.1:8888/v1/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Imh1YW5namciLCJ0b2tlbl92ZXJzaW9uIjoxLCJpc3MiOiJnby1hZG1pbi1taWNyby91c2VyIiwiZXhwIjoxNzY4MzEyMTc1LCJpYXQiOjE3NjgyMjU3NzV9.mZvqqD4moELXYSssxSuJWek6pUTeubrbDqbU1p1Kjyo
Content-Type: application/json

{
  "nickname": "xxx",
  "wallet_addr": ""
}


### 修改用户密码
POST http://127.0.0.1:8888/v1/chpasswd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Imh1YW5namciLCJ0b2tlbl92ZXJzaW9uIjoxLCJpc3MiOiJnby1hZG1pbi1taWNyby91c2VyIiwiZXhwIjoxNzY4MzEyMTc1LCJpYXQiOjE3NjgyMjU3NzV9.mZvqqD4moELXYSssxSuJWek6pUTeubrbDqbU1p1Kjyo
Content-Type: application/json

{
  "old": "huangjg",
  "new": "123456"
}


### 验证码
GET http://127.0.0.1:8888/captcha